name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: go.mod

      - name: Run go vet
        run: go vet ./...

      - name: Check gofmt
        run: |
          fmt_result=$(gofmt -l .)
          if [ -n "$fmt_result" ]; then
            echo "The following files need formatting:"
            echo "$fmt_result"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Snapshot GoReleaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5
        with:
          version: latest
          args: build --snapshot
        env:
          CGO_ENABLED: 0

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -v ./...
